### ISSUE TITLE
SmoothOperator Strategy bug?

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade-strategies#105]
Just tried to test the SmoothOperator from the Repo ... following error coming from the resample function (last section of the code)?

What is wrong here?

```
2020-10-27 22:18:29,931 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy SmoothOperator
2020-10-27 22:18:29,932 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 412, in start
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 613, in ohlcvdata_to_dataframe
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 613, in <dictcomp>
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 629, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/andreas/freqtrade/user_data/strategies/SmoothOperator.py", line 41, in populate_indicators
    dataframe = StrategyHelper.resample(dataframe, self.ticker_interval, self.resample_factor)
  File "/home/andreas/freqtrade/user_data/strategies/SmoothOperator.py", line 325, in resample
    df = df.resample(str(int(interval[:-1]) * factor) + 'min', plotoschow=ohlc_dict)
TypeError: resample() got an unexpected keyword argument 'plotoschow'
```

**Comment by xmatthias** [comment]
Yes, it's a typo (in a function that's not even necessary)
and there's another problem with this strategy, too, once you fix this problem.

i've fixed this now by removing the faulty function (it's outputs were never used anyway).

I'm afraid this can happen with several strategies - as some are just brain-dumps / unfinished strategies which can cause this effect.
