### ISSUE TITLE
'progressbar' has no attribute 'streams'

### ISSUE THREAD

**Issue by al3github** [freqtrade/freqtrade-strategies#123]
Hi,
I get this error when I try to run the following command:
(I have the last version of progressbar (2.5))

home ~/freqtrade$ **freqtrade hyperopt --strategy MACDStrategy --hyperopt MACDStrategy_hyperopt --spaces buy sell**
2021-02-13 09:25:47,532 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\ernesto\appdata\local\programs\python\python38\lib\site-packages\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "c:\users\ernesto\appdata\local\programs\python\python38\lib\site-packages\freqtrade\commands\optimize_commands.py", line 63, in start_hyperopt
    from freqtrade.optimize.hyperopt import Hyperopt
  File "c:\users\ernesto\appdata\local\programs\python\python38\lib\site-packages\freqtrade\optimize\hyperopt.py", line 47, in <module>
    progressbar.streams.wrap_stderr()
AttributeError: module 'progressbar' has no attribute 'streams'

**Comment by xmatthias** [comment]
it seems to me like you've installed the wrong package.

the correct module is progressbar2 - which has the lastest version as 3.53.1.

Best use `pip install -r requirements-hyperopt.txt` to install the dependencies.

**Comment by al3github** [comment]
I see. Thanks!
