### ISSUE TITLE
AttributeError: 'CustomStoplossWithPSAR' object has no attribute 'stoploss'

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade-strategies#141]
```
self._setitem_single_column(loc, value, pi)
2021-03-29 23:50:28,703 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mab/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/mab/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/home/mab/freqtrade/freqtrade/optimize/backtesting.py", line 482, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/mab/freqtrade/freqtrade/optimize/backtesting.py", line 453, in backtest_one_strategy
    results = self.backtest(
  File "/home/mab/freqtrade/freqtrade/optimize/backtesting.py", line 404, in backtest
    trade_entry = self._get_sell_trade_entry(trade, row)
  File "/home/mab/freqtrade/freqtrade/optimize/backtesting.py", line 252, in _get_sell_trade_entry
    sell = self.strategy.should_sell(trade, sell_row[OPEN_IDX],  # type: ignore
  File "/home/mab/freqtrade/freqtrade/strategy/interface.py", line 518, in should_sell
    stoplossflag = self.stop_loss_reached(current_rate=current_rate, trade=trade,
  File "/home/mab/freqtrade/freqtrade/strategy/interface.py", line 573, in stop_loss_reached
    stop_loss_value = force_stoploss if force_stoploss else self.stoploss
AttributeError: 'CustomStoplossWithPSAR' object has no attribute 'stoploss'

```

**Comment by xmatthias** [comment]
This is a demonstration class to demonstrate potential usages of the custom stoploss class.

it's not intended to work as a strategy as is - and the signals are ... questionable at best.

**Comment by mablue** [comment]
Yes but its a good idea.can you add an easy option like that to make stoploss optional?:

stoploss= costumeStopLossGenerator(df['pair'], etc..)

**Comment by xmatthias** [comment]
stoploss is technically optional in the strategy if you have it in the configuration - only if you don't it becomes a required property.
