### ISSUE TITLE
MultiRSI strategy fails on backtesting

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade-strategies#167]
Trying to backtest the [MultiRSI](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/MultiRSI.py) strategy I get this message

<img width="1390" alt="Greenshot 2021-04-30 23 16 17" src="https://user-images.githubusercontent.com/528302/116749766-17c34480-aa0a-11eb-8f2a-b7f7d6986cd6.png">

How can I fix it?

**Comment by xmatthias** [comment]
If you update to the latest / release (make sure to install dependencies, too), technical will be installed automatically.

Otherwise you can use `pip install technical` to install the required module (obviously with the virtualenv activated ...).

**Comment by aristosv** [comment]
I just finished a new installation of freqtrade and tried to backtest this strategy again, but I got this error.

![Uploading Greenshot 2021-05-01 12.03.18.png…]()

**Comment by aristosv** [comment]
I just finished a new installation of freqtrade and tried to backtest this strategy again, but I got this error.

```
2021-05-01 12:01:55,125 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy freqtrade_USDT_aristos
2021-05-01 12:02:19,583 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2020-11-02 00:00:00 up to 2021-05-01 06:00:00 (180 days)..
2021-05-01 12:02:19,587 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/freqtrade_USDT_aristos/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'resample_8_rsi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/optimize/backtesting.py", line 481, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/optimize/backtesting.py", line 457, in backtest_one_strategy
    enable_protections=self.config.get('enable_protections', False),
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/optimize/backtesting.py", line 354, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/optimize/backtesting.py", line 196, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/usr/local/freqtrade_USDT_aristos/freqtrade/strategy/interface.py", line 761, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/usr/local/freqtrade_USDT_aristos/user_data/strategies/freqtrade_USDT_aristos.py", line 37, in populate_buy_trend
    'buy'] = 1
  File "/usr/local/freqtrade_USDT_aristos/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/freqtrade_USDT_aristos/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'resample_8_rsi'
```

**Comment by xmatthias** [comment]
what timeframe are you using this with?

looking at the code, it doesn't seem to be working properly with any timeframe >= 1h - the column namings are potentially broken with that.

WIth the destined timeframe (5m) it does work fine however.

For use with 1h timeframe (which is the one i suspect you're using it with) - you'll need to slightly change how some of the dynamic columns are used.

**Comment by aristosv** [comment]
yes, you're right, I had it at 1h timeframe. I've changed timeframes on other strategies but had no such issues. I had no idea that modifying the timeframe would prevent backtesting from running. Thank you.
