### ISSUE TITLE
class does not exist

### ISSUE THREAD

**Issue by javadpouladi** [freqtrade/freqtrade-strategies#250]
Hello All
im trying to install supertrend strategy for future bot faced error "class does not exist"

> (base) C:\Users\Administrator\freqtrade>conda activate freqtrade-conda

(freqtrade-conda) C:\Users\Administrator\freqtrade>freqtrade trade --config bybit_f.json --strategy f_supertrend_strategy
2022-05-24 07:05:11,756 - freqtrade.worker - INFO - Starting worker develop-0138114fc
2022-05-24 07:05:11,756 - freqtrade.configuration.load_config - INFO - Using config: bybit_f.json ...
2022-05-24 07:05:11,756 - freqtrade.loggers - INFO - Verbosity set to 0
2022-05-24 07:05:11,756 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-05-24 07:05:11,756 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-05-24 07:05:11,756 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-05-24 07:05:11,770 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2022-05-24 07:05:11,770 - freqtrade.configuration.configuration - INFO - Using user-data directory: C:\Users\Administrator\freqtrade\user_data ...
2022-05-24 07:05:11,770 - freqtrade.configuration.configuration - INFO - Using data directory: C:\Users\Administrator\freqtrade\user_data\data\bybit ...
2022-05-24 07:05:11,770 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-05-24 07:05:11,770 - freqtrade.configuration.check_exchange - WARNING - Exchange "bybit" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2022-05-24 07:05:11,770 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-05-24 07:05:11,770 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-0138114fc
2022-05-24 07:05:12,064 - NostalgiaForInfinityX - INFO - pandas_ta successfully imported
2022-05-24 07:05:12,078 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'f_supertrend_strategy'. This class does not exist or contains Python code errors.
2022-05-24 07:05:12,078 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\administrator\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "c:\users\administrator\freqtrade\freqtrade\worker.py", line 35, in __init__
    self._init(False)
  File "c:\users\administrator\freqtrade\freqtrade\worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "c:\users\administrator\freqtrade\freqtrade\freqtradebot.py", line 63, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "c:\users\administrator\freqtrade\freqtrade\resolvers\strategy_resolver.py", line 47, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "c:\users\administrator\freqtrade\freqtrade\resolvers\strategy_resolver.py", line 286, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'f_supertrend_strategy'. This class does not exist or contains Python code errors.

**Comment by xmatthias** [comment]
your startup line assumes that your startegy class is called `f_supertrend_strategy` - which is not found.

This Repository does not contain a class with such a name.
While we do have a supertrend strategy [here](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Supertrend.py) - it's named `Supertrend`  - so this should be your name for the startup line.

**Comment by javadpouladi** [comment]
i used from Futures strategyfolder

**Comment by javadpouladi** [comment]
![Capture](https://user-images.githubusercontent.com/12665054/170070290-6fe18370-44aa-4b6d-a440-1b208f53f98e.PNG)

**Comment by xmatthias** [comment]
Sorry, forgot about these :laughing: 

You're using the filename (`f_supertrend_strategy`) - but you should be using the name (`FSupertrendStrategy`).
