### ISSUE TITLE
Staticmethod objects -> ReinforcedAverageStrategy / ReinforcedQuickie / ReinforcedSmoothScalp

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade-strategies#28]
Just tried to backtest following strategies out of teh repo (no mods):
ReinforcedAverageStrategy / ReinforcedQuickie / ReinforcedSmoothScalp

Got the same error for all of them:
```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 92, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 500, in start
    backtesting = Backtesting(config)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 88, in __init__
    self.strategylist.append(StrategyResolver(self.config).strategy)
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 40, in __init__
    extra_dir=config.get('strategy_path'))
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 161, in _load_strategy
    return import_strategy(strategy, config=config)
  File "/root/freqtrade/freqtrade/strategy/__init__.py", line 28, in import_strategy
    attr = deepcopy(comb)
  File "/root/miniconda3/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/miniconda3/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/miniconda3/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle staticmethod objects
```

**Comment by xmatthias** [comment]
I added a fix for that since it's just a python / pickle specific problem - should be merged soonish
