### ISSUE TITLE
How to get funding rate to use as indicator on freqtrade

### ISSUE THREAD

**Issue by dekacypher** [freqtrade/freqtrade-strategies#280]
I'm trying to add funding rate as a parameter on the dataframe for perpetual futures with OHLC, in order to use it as an indicator for when to buy and sell on futures trading.
**The dataframe:**

`
                       date     open     high      low    close      volume                   date_8h  ...  bb_upperband  bb_percent  bb_width           sar  tema  htsine  htleadsine
0 2022-11-22 00:00:00+00:00  15772.9  15960.0  15610.3  15754.9  161681.159 2022-11-22 00:00:00+00:00  ...           NaN         NaN       NaN           NaN   NaN     NaN         NaN
1 2022-11-22 08:00:00+00:00  15754.9  16309.0  15653.8  16232.8  285745.047 2022-11-22 08:00:00+00:00  ...  16330.443828    0.881012  0.051546  15610.300000   NaN     NaN         NaN
2 2022-11-22 16:00:00+00:00  16232.8  16282.4  16040.0  16220.6  131907.438 2022-11-22 16:00:00+00:00  ...  16425.314396    0.755258  0.052255  15624.274000   NaN     NaN         NaN
3 2022-11-23 00:00:00+00:00  16220.5  16659.1  16155.5  16572.9  188167.927 2022-11-23 00:00:00+00:00  ...  16690.158377    0.897000  0.070618  15637.968520   NaN     NaN         NaN
4 2022-11-23 08:00:00+00:00  16572.9  16694.0  16338.0  16415.9  180403.275 2022-11-23 08:00:00+00:00  ...  16782.909067    0.688780  0.072824  15678.813779   NaN     NaN         NaN
5 2022-11-23 16:00:00+00:00  16415.9  16703.4  16313.1  16595.8  178143.708 2022-11-23 16:00:00+00:00  ...  16848.209772    0.788803  0.073544  15739.724952   NaN     NaN         NaN

`

I've tried adding informative pairs `@informative('8h', candle_type= "funding_rate")` before the `populate_indicators` method after downloading the futures data with `freqtrade download-data --trading-mode futures --pairs ETH/USDT --timeframe 8h --candle-types funding_rate`.

I've researched and read the documentation for a solution with no luck. I'm kindly asking for your help.

**Comment by xmatthias** [comment]
`@informative('8h', candle_type= "funding_rate")` should work just fine - but not on `populate_indicators` - but on a separate function (that's not called populate_indicators - so it's then available in populate_indicators). (documented [here](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative).

It'll also only work if you're in futures markets (not in spot markets) - at least in dry-run.


default funding rates (default 8h, can vary between exchanges)  are also downloaded automatically when you download regular futures data, so the explicit step will be unnecessary.

**Comment by dekacypher** [comment]
**The separate function i added the informative pairs in is as such:**
` @informative('8h', candle_type='funding_rate')
    def populate_indicators_(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe)
        return dataframe
`
**Including the timeframe is necessary as it hinders the arising of this error code:**

`ftuser@dfb252944e06:/freqtrade$ freqtrade backtesting --strategy PLTStrategy
2022-12-23 13:48:12,553 - freqtrade - INFO - freqtrade docker-2022.12.dev-cb81613a
2022-12-23 13:48:12,592 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-12-23 13:48:12,606 - freqtrade.loggers - INFO - Verbosity set to 0
2022-12-23 13:48:12,609 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2022-12-23 13:48:13,279 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-12-23 13:48:13,280 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-12-23 13:48:13,280 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-12-23 13:48:13,282 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-12-23 13:48:13,315 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-12-23 13:48:13,315 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-12-23 13:48:13,315 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-12-23 13:48:13,325 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-12-23 13:48:13,328 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-12-23 13:48:13,328 - freqtrade.exchange.exchange - INFO - Using CCXT 2.2.92
2022-12-23 13:48:13,330 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-12-23 13:48:13,429 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-12-23 13:48:13,453 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-12-23 13:48:14,600 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-12-23 13:48:14,742 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 57, in start_backtesting
    backtesting = Backtesting(config)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 104, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(self.config))
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 256, in _load_strategy
    strategy = StrategyResolver._load_object(
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 148, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 130, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 91, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/freqtrade/user_data/strategies/PLTStrategy.py", line 21, in <module>
    class PLTStrategy(IStrategy):
  File "/freqtrade/user_data/strategies/PLTStrategy.py", line 145, in PLTStrategy
    @informative(candle_type='funding_rate')
TypeError: informative() missing 1 required positional argument: 'timeframe'
`

**Comment by xmatthias** [comment]
well nobody said otherwise :)

**Comment by aishamh** [comment]
Your suggestion doesn't work.

**Comment by xmatthias** [comment]
well what you tried after my comment is NOT what i suggested - but something else.

something around this should work - ASSUMING you are on futures markets.

```
    @informative('8h', candle_type='funding_rate')
    def populate_indicators_funding(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe)
        return dataframe
```

**Comment by aishamh** [comment]
Alright, I'll update you

**Comment by aishamh** [comment]
The timeframe is 8h, but my intention is to include funding rate as a olumn in the dataframe, in order to use it as an indicator. The dataframe that is returned includes, when i add `populate_indicators_funding` function:

`date              True
open              True
high              True
low               True
close             True
volume            True
date_8h           True
open_8h           True
high_8h          False
low_8h           False
close_8h         False
volume_8h        False
rsi_8h           False
adx               True
rsi               True
fastd             True
fastk             True
macd              True
macdsignal        True
macdhist          True
mfi               True
bb_lowerband      True
bb_middleband     True
bb_upperband      True
bb_percent        True
bb_width          True
sar               True
tema              True
htsine            True
htleadsine        True
enter_long        True
enter_short       True`

But it doesn't include funding rate as a column, which is a negative or positive float value that indicates whether the market is bearish and the short traders pay a funding fee to the long traders, or the opposite. I'm not sure if you misunderstood it as something else, but are we on the same page?
