### ISSUE TITLE
Unable to retrieve candlestick information from dataframe

### ISSUE THREAD

**Issue by azubu23202869** [freqtrade/freqtrade-strategies#296]
```python
    def ott(self, dataframe: DataFrame):
        df = dataframe.copy()

        def Reversal123(Length, KSmoothing, DLength, Level):
            vFast = ta.SMA(ta.STOCH(df["close"].shift(1), df["high"].shift(1), df["low"].shift(1), Length), KSmoothing)
            vSlow = ta.SMA(vFast, DLength)
            pos = pd.Series(0.0, index=close.index)
            pos = 1 if df["close"].shift(3) < df["close"].shift(2) and df["close"].shift(1) > df["close"].shift(2) and vFast < vSlow and vFast > Level else -1 if df["close"].shift(3) > df["close"].shift(2) and df["close"].shift(1) < df["close"].shift(2) and vFast > vSlow and vFast < Level else nz(pos[1], 0)
            return pos

        def SMI(length, tf):
            pos = 0.0
            nRes = 0.0
            xcloseH1 = df["close"].shift(1)
            xopenH1 = df["open"].shift(1) 
            nRes = bt_safe_div((nRes[-1], 1) - (o - c) + (xopenH1 - xcloseH1)) 
            xSmaRes = ta.SMA(nRes, length)
            pos = ta.IFF(xSmaRes > nRes, 1,
                    ta.IFF(xSmaRes < nRes, -1, ta.NZ(pos[-1], 0)))
            return pos

        posReversal123 = Reversal123(14, 1, 3, 50)
        posSMI = SMI(18, False)
        pos = 1 if posReversal123 == 1 and posSMI == 1 else -1 if posReversal123 == -1 and posSMI == -1 else 0
        possig = -1 if reverse and pos == 1 else 1 if reverse and pos == -1 else pos
        df["possig"] = possig

        return DataFrame(index=df.index, data={"possig": df["possig"]})
```

Error Msg

```diff
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1344, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1246, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in advise_all_indicators
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/Test2.py", line 96, in populate_indicators
    dataframe["possig"] = self.ott(dataframe)["possig"]
  File "/freqtrade/user_data/strategies/Test2.py", line 160, in ott
    posReversal123 = Reversal123(14, 1, 3, 50)
  File "/freqtrade/user_data/strategies/Test2.py", line 143, in Reversal123
    vFast = ta.SMA(ta.STOCH(df["close"].shift(1), df["high"].shift(1), df["low"].shift(1), Length), KSmoothing)
  File "talib/_abstract.pxi", line 442, in talib._ta_lib.Function.__call__
TypeError: Not enough price arguments: expected 1 (close)
```

I don't understand why this error is occurring.

**Comment by xmatthias** [comment]
assuming you use "abstract" imports (`import talib.abstract as ta` - which basically all of our samples do) - then the data you provide to `ta.STOCH` is wrong - as it expects a dataframe (or one series), not 3 price-series.

I'd suggest to split this line out into 2 (so it's clear which line fails) - and then look at the ta-lib documentation to see what arguments exactly the failing function expects / requires.
