### ISSUE TITLE
hyperopts for the strategies

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade-strategies#33]
All the strategies published in freqtrade-strategies should be supplied with corresponding Hyperopts to adjust the constants used in them basing on actual historical data.

For example:
There should be MACDHyperopt for the MACDStrategy (https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/MACDStrategy.py) which would allow to adjust upper and lower borders for CCI band, which is now hardcoded to (-50.0, 100.0), as well as to select best roi and stoploss.

**Comment by berlinguyinca** [comment]
great suggestions

**Comment by OtenMoten** [comment]
Hello dear community,

I wrote the hyper-optimization for the `AverageStrategy.py` strategy from [github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/AverageStrategy.py) written by @berlinguyinca 

I've created a pull-request and when it's reviewd I will link it here. <br>
[ >>> PLACEHOLDER <<<]

It seems to be a nice idea to gather all the hyper-optimization related to the strategies from @berlinguyinca here in this issue.

I wondered about the range of the moving average, therefore I created a hyper-optimization that calculates the sweet-spot for buy and sell when short-ma and medium-ma cross above and vice versa. I.E.: @berlinguyinca used in his version of `AverageStrategy.py` the timeframes for `ma-short = 8` and `ma-medium = 21`. I want to know what are the best timeframes beside `8` and `21`. So, the algorithm is looping through all the different timeframes of the both moving averages.

Hopefully you get value from this.

Kind regards
Kevin

**Comment by gerardsimons** [comment]
Hey there, great work there. I am facing some issues though. I am trying to run your HyperOpt class lik so :

`freqtrade hyperopt --config config.json --hyperopt AverageHyperopt --hyperopt-loss ShortTradeDurHyperOptLoss --strategy AverageStrategy -e 500 `

but keep getting this error : 

```
Traceback (most recent call last):
  File "/home/gerard/Git/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/gerard/Git/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/gerard/Git/freqtrade/freqtrade/optimize/hyperopt.py", line 713, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/space/space.py", line 1132, in distance
    distance += dim.distance(a, b)
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/space/space.py", line 737, in distance
    if not (a in self and b in self):
  File "/home/gerard/.miniconda3/envs/freqtrade/lib/python3.8/site-packages/skopt/space/space.py", line 714, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by xmatthias** [comment]
Best follow https://github.com/freqtrade/freqtrade/issues/3796 - it also contains a workaround until the issue is further debugged.

Feel free to help investigate what changed in scikit-learn / scikit-optimize that led to this changed behaviour ... as neither changelog mention this explicitly.

**Comment by gerardsimons** [comment]
@xmatthias : Thanks, i'll take a look!

**Comment by xmatthias** [comment]
with the possibility of hyperoptable parameters within the strategy, i don't see this as relevant any longer.

Parameters can pretty easily be added - and it should be seen as a good learning experience do to this for strategies that don't have that already.
