### ISSUE TITLE
ImportError: cannot import name 'parse_ticker_dataframe'

### ISSUE THREAD

**Issue by senzacionale** [freqtrade/freqtrade-strategies#72]
When executing

`freqtrade backtesting --strategy-list ADXMomentum ClucMay72018 MACDStrategy_crossed Simple AdxSmas CMCWinner MACDStrategy ASDTSRockwellTrading CofiBitStrategy SmoothScalp AverageStrategy CombinedBinHAndCluc DoesNothingStrategy Quickie BbandRsi EMASkipPump ReinforcedQuickie ReinforcedSmoothScalp CCIStrategy Low_BB Scalp --ticker-interval=1h --timerange=20190101-`

I am getting error. Looks like something was changed in the meanwhile.
```

Traceback (most recent call last):
  File "/home/adin/TradingBot/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/adin/TradingBot/freqtrade/freqtrade/commands/optimize_commands.py", line 48, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/adin/TradingBot/freqtrade/freqtrade/optimize/backtesting.py", line 79, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(stratconf))
  File "/home/adin/TradingBot/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    extra_dir=config.get('strategy_path'))
  File "/home/adin/TradingBot/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 165, in _load_strategy
    kwargs={'config': config})
  File "/home/adin/TradingBot/freqtrade/freqtrade/resolvers/iresolver.py", line 108, in _load_object
    object_name=object_name)
  File "/home/adin/TradingBot/freqtrade/freqtrade/resolvers/iresolver.py", line 92, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/home/adin/TradingBot/freqtrade/freqtrade/resolvers/iresolver.py", line 61, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adin/TradingBot/freqtrade/user_data/strategies/InformativeSample.py", line 7, in <module>
    from freqtrade.data.converter import parse_ticker_dataframe
ImportError: cannot import name 'parse_ticker_dataframe'
```

Can you please help?

**Comment by senzacionale** [comment]
Fixed sorry

**Comment by xmatthias** [comment]
Best update your strategy repository (?) 

The error seems to come from `InformativeSample` - but looking at the file (https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/InformativeSample.py) , it does not import (nor use) `parse_ticker_dataframe()`, so either you use a modified version - or an old / outdated version of the InformativeSample strategy.

**Comment by senzacionale** [comment]
Correct. I used old version. Sorry again.
